Brubrux/Proyecto-AnInfo-

- README.md
- main.py
> ¡Hola mundo!

- palabras.json
Agrego el archivo palabras.json, que tiene la base de datos con las palabras para jugar al ahorcado.
> Creo base de datos con las palabras que se van a usar para jugar

- main.py
- status.py
Closes #7 
- Se ha agregado la función print_status al código, la cual se encarga de imprimir el estado del juego en la terminal. 
- Se creo el modulo status.py para implementar esta issue.
- Se ha agregado un nuevo conjunto de pruebas unitarias utilizando la biblioteca unittest.
- Las pruebas unitarias testean la salida estandar de print_status
> Agrego mensaje del estado del juego

- dificultad.py
- main.py
La clase recibe tres parámetros: palabras, cantidad de intentos y cantidad de pistas
El tipo de dificultad dependerá de estos tres parámetros. Cuando se quiera elegir una dificultad se tendrá que instanciar esta clase con los parámetros correspondientes. Por ejemplo, si es fácil entonces sus parámetros serán:
- Lista de palabras fáciles de la base de datos
- Cantidad de intentos igual a 7
- Cantidad de pistas igual a 3
Por el momento decidí implementar solo una clase Dificultad que generalice las tres dificultades ya que solo se diferencian en estos 3 atributos.
> Creando la clase Dificultad

- main.py
> 25 feature opción de empezar partida interfaz del juego

- dificultad.py
- main.py
Closes #3 #19  
Implementaciones de pedir palabra  (#19) y guardar letras (#3)
> Bruno branch

- dificultad.py
- estado_juego.py
- juego_ahorcado.py
- main.py
- main_menu.py
El usuario debe poder seleccionar el nivel de dificultad
Closes #27 
- Implementé la lógica para seleccionar el nivel de dificultad
- Hice un refactor del archivo main_menu, creando una clase MenuJuego y un enum OpcionesMenu para que el código sea mas claro y legible
- Eliminé el estado del juego "abandonado" porque no era necesario utilizarlo
El código está abierto a cambios. Es probable que encuentren nombres más descriptivos para algunas funciones, ej: from_input
> 27 feature opcion de seleccionar nivel de dificultad interfaz del juego

- juego_ahorcado.py
- main_menu.py
Closes #22 
Se limpia la consola con cada input y se imprime lo pertinente. Sean libres de testear y decirme de algun caso borde que no haya tenido en cuenta. 
Esta issue se tiene que reveer luego de agregar el ascii art y para cada pantalla que se agregue.
> se limpia la consola con el modulo os

- estado_juego.py
- juego_ahorcado.py
Closes #5 
- Se colocan todas las letras una vez que la palabra es adivinada por completo y cuando se pierde la partida.
> colocar letra en espacio pertinente

- juego_ahorcado.py
Para que al perder se desvele la palabra que el jugador no pudo adivinar, en el método de la clase JuegoAhorcado que muestra la palabra primero verificamos el estado del juego. Si el estado del juego no es "EN CURSO" entonces se muestra por consola cada letra.
Ademas, en el método que muestra el estado, si el estado del juego no es "EN CURSO" entonces el jugador deberá presionar ENTER para volver a la pantalla del menú principal.
> Verificar victoria o derrota

- api.py
Closes #21 
Ahora el juego se ve más bonito con un ahorcado en ASCII que se va armando conforme el jugador comete errores. 
¡Espero que les guste!
> Print del ahorcado listo

- juego_ahorcado.py
- main_menu.py
Closes #50  
- Se le avisa al usuario que el input es inválido cuando intenta ingresar un caracter nulo o un espacio (" "), suponiendo que pudo haber sido accidentalmente
- No se consideran los espacios (" ") en las palabras ingresadas que empiecen y/o terminen con alguno/s de estos
- No se diferencia entre mayúsculas y minúsculas
> verificacion de input

- dificultad.py
- estado_juego.py
- juego_ahorcado.py
- main_menu.py
- options/game_options.py
- options/menu_options.py
> Refactor general

- game.py
- main.py
- menu.py
- options/game.py
En muchos archivos, los imports quedaron con nombres viejos de las bibliotecas utilizadas por estos, por lo que hizo falta actualizar los imports con los nuevos nombres.
Corrección de imports para cada archivo renombrado en el refactor anterior.
> fix de imports

- game.py
- menu.py
- options/game.py
- options/menu.py
- utils.py
> [BUG] Adaptar limpieza de pantalla para windows

- controller.py
- difficulty.py
- game.py
- menu.py
- palabras.json
- word_category.py
Closes #55
- Se definieron las categorías: aninfo, famosos, peliculas y series, animales
- Se creó una nueva interfaz para mostrar las categorías y que el usuario pueda seleccionar con cual jugar
- Se creó un enum de categorías al cual se le implementaron algunas funciones
- Se implementó la lógica para que el usuario pueda jugar una partida con una palabra random correspondiente a la categoría y dificultad seleccionadas
> 55 feature categorizar palabras del ahorcado

- clue_handler.py
- controller.py
- game.py
- menu.py
- options/game.py
- options/menu.py
- user_statistics.py
Cree el objeto ClueHandler que ayuda a manejar las pistas, y ahora se puede comprar pistas desde afuera y adentro del juego
> [FEATURE] Comprar pistas con puntos

- menu.py
- options/menu.py
- test.sh
Closes #40 
Agrego test unitarios de GameMenu de menu.py
Observaciones:
- Cree wraps para algunos metodos porque testear el clear es muy complejo y no creo que valga la pena.
- Comente un import de option.menu porque era un import ciclico y lo detectaban los tests
- Estos test validan los metodos de ouput de Game Menu
- Se recomienda ejecutar el bash del test con los siguientes pasos: 1) chmod +x test.sh  2) ./test.sh
>  [40] [Test] Testear Game Menu

- dependencies.py
Closes #79 
- instalador de dependencias implementado: Se instalan 'pip' y el paquete unicode si no están instalados.
> 79 feature instalador de dependencias

- src/menu.py
- src/session_handler.py
El error consistia que el programa dejaba de funcionar cuando el usuario queria salir del juego sin iniciar seccion. El comportamiento del programa no era lo esperado porque terminaba bruscamente.
- Al salir del programa ahora se devuelve una tupla de 4 None
- Se agrego un clear cuando se muestran las dificultades
> [BUG] Error al salir sin iniciar seccion
